//#region 'API CALLS'
export const BEGIN_API_CALL = 'BEGIN_API_CALL'
export const API_CALL_ERROR = 'API_CALL_ERROR'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS'
export const COMPLETE_COURSE = 'COMPLETE_COURSE'
export const DELETE_COURSE = 'DELETE_COURSE'
export const ADD_COURSE = 'ADD_COURSE'

export const LOAD_COURSE_BY_ID_SUCCESS = 'LOAD_COURSE_BY_ID_SUCCESS'
//#endregion

export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const LOG_OUT_USER = 'LOG_OUT_USER'
